models/Players.php
<?php
namespace app\models;

use yii\db\ActiveRecord;
use app\models\Team;

class Players extends ActiveRecord
{

    public static function tableName()
    {
        return 'players';
    }

    public function rules()
    {
        return[
            [['name','surname','birth_date','position','team_id'],'required']
        ];
    }

    public function getTeam()
    {
        return $this->hasOne(Team::className(),['id' => 'team_id']);
    }

    public function attributeLabels()
    {
        return [
            'id'=> 'id',
            'name'=>'name',
            'surname'=> 'surname',
            'birth_date'=> 'birth_date',
            'position'=> 'position',
            'team_id'=> 'team_id'
        ];
    }

}

models/Team.php
<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 01.03.2017
 * Time: 18:29
 */

namespace app\models;

use yii\db\ActiveRecord;
use app\models\Players;
use yii\helpers\ArrayHelper;

class Team extends ActiveRecord
{

    public static function tableName()
    {
        return 'team';
    }

    public function rules()
    {
        return [
            [['name','foundation_date'],'required'],
        ];
    }

    public function getPlayers()
    {
        return $this->hasMany(Players::className(),['team_id' => 'id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Players;
use app\models\Team;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * Displays homepage.
     *
     * @return string
     */

    public function actionIndex()
    {
        $this->view->title='Football.yii';
        $model=Team::find()->all();
        return $this->render('index.twig',['model' => $model]);
    }

    public function actionCreateTeam()
    {
     $this->view->title='Create team';
        $model=new Team();
        if($model->load(Yii::$app->request->post())&&$model->validate()) {
            if($model->save()) {
                Yii::$app->session->setFlash('create_team_success');
            }
        }
        return $this->render('create_team.twig',['model' => $model]);
    }

    public function actionViewTeam($id)
    {
     $model=Team::findOne($id);
     $this->view->title=$model->name;
        return $this->render('team_view.twig',['model' => $model]);
    }

    public function actionPlayerCreate($id=null)
    {
        if($id!=null) {
            $this->view->title = 'Create player';
            $model = new Players();
            $team = Team::findOne($id);
            if ($model->load(Yii::$app->request->post())) {
                $model->team_id = $team->id;
                if ($model->save()) {
                    Yii::$app->session->setFlash('create_player_success');
                }
            }
            return $this->render('create_player.twig', [
                'model' => $model,
                'team' => $team
            ]);
        }
        else {
            $all_pl_create=1;
            $model= new Players();
            $teams=ArrayHelper::map(Team::find()->asArray()->all(),'id','name');
            if($model->load(Yii::$app->request->post())&&$model->validate())
            {
                if($model->save())
                {
                    Yii::$app->session->setFlash('create_player_success');
                }
            }
            return $this->render('create_player.twig',[
                'model' => $model,
                'teams' => $teams,
                'all_pl_create' => $all_pl_create
            ]);
        }
    }

    public function actionTeamUpdate($id)
    {
        $model=Team::findOne($id);
        $this->view->title=$model->name;
        if($model->load(Yii::$app->request->post())&&$model->validate()) {
            if($model->save()) {
                Yii::$app->session->setFlash('update_team_success');
            }
        }
        return $this->render('team_update.twig',['model' => $model]);
    }

    public function actionPlayerView($id)
    {
        $model=Players::findOne($id);
        $this->view->title=$model->surname;
        return $this->render('player_view.twig',['model' => $model]);
    }

    public function actionPlayerUpdate($id)
    {
        $model=Players::findOne($id);
        $this->view->title=$model->surname;
        $teams=ArrayHelper::map(Team::find()->asArray()->all(),'id','name');
        if($model->load(Yii::$app->request->post())&&$model->validate()) {
            if($model->save()) {
                Yii::$app->session->setFlash('player_update_success');
            }
        }
        return $this->render('player_update.twig',[
            'model' => $model,
            'teams' => $teams
        ]);
    }

    public function actionPlayerDelete($id)
    {
        $model=Players::findOne($id);
        if($model->delete()) {
            Yii::$app->session->setFlash('delete_player_success');
        }
        return $this->render('player_view.twig');
    }

    public function actionTeamDelete($id)
    {
        $model=Team::findOne($id);
        if($model->delete()) {
            if($players = Players::deleteAll(['team_id' => $id])) {
            }
             Yii::$app->session->setFlash('team_delete_success');
             return $this->render('player_view.twig');
        }
    }

    public function actionAllPlayers()
    {
        $model=Players::find()->all();
        return $this->render('all_players.twig',['model' => $model]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Football',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'All players', 'url' => ['/site/all-players']]

        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">

    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>